---
version: '3.1'

services:

  mongo:
    image: mongo
    deploy:
      replicas: 1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user 
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: Velov
    volumes:
      - ./initdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    deploy:
      replicas: 1
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@mongo:27017/

  mosquitto:
    image: eclipse-mosquitto
    depends_on:
      - mongo
    deploy:
      replicas: 1
    restart: always
    volumes:
      - ../DOCKER_MOSQUITTO/config/:/mosquitto/config/
    ports:
      - 1883:1883
      - 9001:9001

  grafana:
    image: grafana/grafana
    depends_on:
      - backend
    deploy:
      replicas: 1
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
      GF_SECURITY_ADMIN_PASSWORD: password

    volumes:
      - ../DOCKER_GRAFANA/grafana:/etc/grafana/provisioning/

  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  backend:
    depends_on:
      - mosquitto
      - mongo
    image: camilcll/docker_python
    deploy:
      replicas: 1
    ports:
      - "8888:8888"
    restart: always
