---
version: '3.1'

services:

  mongo:
    image: mongo
    deploy:
      replicas: 3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user 
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: Velov

  mongo-express:
    image: mongo-express
    deploy:
      replicas: 2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@mongo:27017/

  mosquitto:
    image: eclipse-mosquitto
    deploy:
      replicas: 2
    restart: always
    volumes:
      - ../DOCKER_MOSQUITTO/config/:/mosquitto/config/:ro
      - ../DOCKER_MOSQUITTO/log/:/mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001

  grafana:
    image: grafana/grafana
    deploy:
      replicas: 2
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
      GF_SECURITY_ADMIN_PASSWORD: password

    volumes:
      - ../DOCKER_GRAFANA/grafana:/etc/grafana/provisioning/

  visualizer:
    image: dockersamples/visualizer
    deploy:
      replicas: 2
    ports:
      - "8080:8080"
    restart: always

  backend:
    deploy:
      replicas: 2
    ports:
      - "8888:8888"
    restart: always
    build: ../Back-End

volumes:
  data: